/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteRouteImport } from './routes/_home/route'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as HomeIndexRouteImport } from './routes/_home/index'
import { Route as HomeServicesRouteImport } from './routes/_home/services'
import { Route as HomeLegalRouteImport } from './routes/_home/legal'
import { Route as HomeContactRouteImport } from './routes/_home/contact'
import { Route as HomeAboutRouteImport } from './routes/_home/about'
import { Route as DashboardWithdrawRouteImport } from './routes/_dashboard/withdraw'
import { Route as DashboardWatchlistRouteImport } from './routes/_dashboard/watchlist'
import { Route as DashboardStrategiesRouteImport } from './routes/_dashboard/strategies'
import { Route as DashboardStocksRouteImport } from './routes/_dashboard/stocks'
import { Route as DashboardStockWithdrawRouteImport } from './routes/_dashboard/stock-withdraw'
import { Route as DashboardStockDepositRouteImport } from './routes/_dashboard/stock-deposit'
import { Route as DashboardStakesRouteImport } from './routes/_dashboard/stakes'
import { Route as DashboardRequestRouteImport } from './routes/_dashboard/request'
import { Route as DashboardReferralsRouteImport } from './routes/_dashboard/referrals'
import { Route as DashboardProfileRouteImport } from './routes/_dashboard/profile'
import { Route as DashboardPortfolioRouteImport } from './routes/_dashboard/portfolio'
import { Route as DashboardMarketTrendsRouteImport } from './routes/_dashboard/market-trends'
import { Route as DashboardLogoutRouteImport } from './routes/_dashboard/logout'
import { Route as DashboardHistoryRouteImport } from './routes/_dashboard/history'
import { Route as DashboardDiscoverRouteImport } from './routes/_dashboard/discover'
import { Route as DashboardDepositRouteImport } from './routes/_dashboard/deposit'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as DashboardCoinRouteImport } from './routes/_dashboard/coin'
import { Route as DashboardBuyStocksRouteImport } from './routes/_dashboard/buy-stocks'
import { Route as AuthSkipRouteImport } from './routes/_auth/skip'
import { Route as AuthSectorRouteImport } from './routes/_auth/sector'
import { Route as AuthOperationsRouteImport } from './routes/_auth/operations'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthKycRouteImport } from './routes/_auth/kyc'
import { Route as AuthForgotRouteImport } from './routes/_auth/forgot'
import { Route as AuthCreateRouteImport } from './routes/_auth/create'
import { Route as AdminUsersRouteImport } from './routes/_admin/users'
import { Route as AdminTransactionsRouteImport } from './routes/_admin/transactions'
import { Route as AdminStockRouteImport } from './routes/_admin/stock'
import { Route as AdminStaffRouteImport } from './routes/_admin/staff'
import { Route as AdminSettingsRouteImport } from './routes/_admin/settings'
import { Route as AdminRequestsRouteImport } from './routes/_admin/requests'
import { Route as AdminPlansRouteImport } from './routes/_admin/plans'
import { Route as AdminNotificationsRouteImport } from './routes/_admin/notifications'
import { Route as AdminInvestmentsRouteImport } from './routes/_admin/investments'
import { Route as AdminDepositRequestsRouteImport } from './routes/_admin/depositRequests'
import { Route as AdminAdminReferralRouteImport } from './routes/_admin/adminReferral'
import { Route as AdminAdminProfileRouteImport } from './routes/_admin/adminProfile'

const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeServicesRoute = HomeServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeLegalRoute = HomeLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeContactRoute = HomeContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeAboutRoute = HomeAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => HomeRouteRoute,
} as any)
const DashboardWithdrawRoute = DashboardWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardWatchlistRoute = DashboardWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardStrategiesRoute = DashboardStrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardStocksRoute = DashboardStocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardStockWithdrawRoute = DashboardStockWithdrawRouteImport.update({
  id: '/stock-withdraw',
  path: '/stock-withdraw',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardStockDepositRoute = DashboardStockDepositRouteImport.update({
  id: '/stock-deposit',
  path: '/stock-deposit',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardStakesRoute = DashboardStakesRouteImport.update({
  id: '/stakes',
  path: '/stakes',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRequestRoute = DashboardRequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardReferralsRoute = DashboardReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPortfolioRoute = DashboardPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMarketTrendsRoute = DashboardMarketTrendsRouteImport.update({
  id: '/market-trends',
  path: '/market-trends',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLogoutRoute = DashboardLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDiscoverRoute = DashboardDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDepositRoute = DashboardDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCoinRoute = DashboardCoinRouteImport.update({
  id: '/coin',
  path: '/coin',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBuyStocksRoute = DashboardBuyStocksRouteImport.update({
  id: '/buy-stocks',
  path: '/buy-stocks',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthSkipRoute = AuthSkipRouteImport.update({
  id: '/skip',
  path: '/skip',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSectorRoute = AuthSectorRouteImport.update({
  id: '/sector',
  path: '/sector',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthOperationsRoute = AuthOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthKycRoute = AuthKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCreateRoute = AuthCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStockRoute = AdminStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInvestmentsRoute = AdminInvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDepositRequestsRoute = AdminDepositRequestsRouteImport.update({
  id: '/depositRequests',
  path: '/depositRequests',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminReferralRoute = AdminAdminReferralRouteImport.update({
  id: '/adminReferral',
  path: '/adminReferral',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminProfileRoute = AdminAdminProfileRouteImport.update({
  id: '/adminProfile',
  path: '/adminProfile',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/adminProfile': typeof AdminAdminProfileRoute
  '/adminReferral': typeof AdminAdminReferralRoute
  '/depositRequests': typeof AdminDepositRequestsRoute
  '/investments': typeof AdminInvestmentsRoute
  '/notifications': typeof AdminNotificationsRoute
  '/plans': typeof AdminPlansRoute
  '/requests': typeof AdminRequestsRoute
  '/settings': typeof AdminSettingsRoute
  '/staff': typeof AdminStaffRoute
  '/stock': typeof AdminStockRoute
  '/transactions': typeof AdminTransactionsRoute
  '/users': typeof AdminUsersRoute
  '/create': typeof AuthCreateRoute
  '/forgot': typeof AuthForgotRoute
  '/kyc': typeof AuthKycRoute
  '/login': typeof AuthLoginRoute
  '/operations': typeof AuthOperationsRoute
  '/sector': typeof AuthSectorRoute
  '/skip': typeof AuthSkipRoute
  '/buy-stocks': typeof DashboardBuyStocksRoute
  '/coin': typeof DashboardCoinRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/deposit': typeof DashboardDepositRoute
  '/discover': typeof DashboardDiscoverRoute
  '/history': typeof DashboardHistoryRoute
  '/logout': typeof DashboardLogoutRoute
  '/market-trends': typeof DashboardMarketTrendsRoute
  '/portfolio': typeof DashboardPortfolioRoute
  '/profile': typeof DashboardProfileRoute
  '/referrals': typeof DashboardReferralsRoute
  '/request': typeof DashboardRequestRoute
  '/stakes': typeof DashboardStakesRoute
  '/stock-deposit': typeof DashboardStockDepositRoute
  '/stock-withdraw': typeof DashboardStockWithdrawRoute
  '/stocks': typeof DashboardStocksRoute
  '/strategies': typeof DashboardStrategiesRoute
  '/watchlist': typeof DashboardWatchlistRoute
  '/withdraw': typeof DashboardWithdrawRoute
  '/about': typeof HomeAboutRoute
  '/contact': typeof HomeContactRoute
  '/legal': typeof HomeLegalRoute
  '/services': typeof HomeServicesRoute
  '/': typeof HomeIndexRoute
}
export interface FileRoutesByTo {
  '/adminProfile': typeof AdminAdminProfileRoute
  '/adminReferral': typeof AdminAdminReferralRoute
  '/depositRequests': typeof AdminDepositRequestsRoute
  '/investments': typeof AdminInvestmentsRoute
  '/notifications': typeof AdminNotificationsRoute
  '/plans': typeof AdminPlansRoute
  '/requests': typeof AdminRequestsRoute
  '/settings': typeof AdminSettingsRoute
  '/staff': typeof AdminStaffRoute
  '/stock': typeof AdminStockRoute
  '/transactions': typeof AdminTransactionsRoute
  '/users': typeof AdminUsersRoute
  '/create': typeof AuthCreateRoute
  '/forgot': typeof AuthForgotRoute
  '/kyc': typeof AuthKycRoute
  '/login': typeof AuthLoginRoute
  '/operations': typeof AuthOperationsRoute
  '/sector': typeof AuthSectorRoute
  '/skip': typeof AuthSkipRoute
  '/buy-stocks': typeof DashboardBuyStocksRoute
  '/coin': typeof DashboardCoinRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/deposit': typeof DashboardDepositRoute
  '/discover': typeof DashboardDiscoverRoute
  '/history': typeof DashboardHistoryRoute
  '/logout': typeof DashboardLogoutRoute
  '/market-trends': typeof DashboardMarketTrendsRoute
  '/portfolio': typeof DashboardPortfolioRoute
  '/profile': typeof DashboardProfileRoute
  '/referrals': typeof DashboardReferralsRoute
  '/request': typeof DashboardRequestRoute
  '/stakes': typeof DashboardStakesRoute
  '/stock-deposit': typeof DashboardStockDepositRoute
  '/stock-withdraw': typeof DashboardStockWithdrawRoute
  '/stocks': typeof DashboardStocksRoute
  '/strategies': typeof DashboardStrategiesRoute
  '/watchlist': typeof DashboardWatchlistRoute
  '/withdraw': typeof DashboardWithdrawRoute
  '/about': typeof HomeAboutRoute
  '/contact': typeof HomeContactRoute
  '/legal': typeof HomeLegalRoute
  '/services': typeof HomeServicesRoute
  '/': typeof HomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/_home': typeof HomeRouteRouteWithChildren
  '/_admin/adminProfile': typeof AdminAdminProfileRoute
  '/_admin/adminReferral': typeof AdminAdminReferralRoute
  '/_admin/depositRequests': typeof AdminDepositRequestsRoute
  '/_admin/investments': typeof AdminInvestmentsRoute
  '/_admin/notifications': typeof AdminNotificationsRoute
  '/_admin/plans': typeof AdminPlansRoute
  '/_admin/requests': typeof AdminRequestsRoute
  '/_admin/settings': typeof AdminSettingsRoute
  '/_admin/staff': typeof AdminStaffRoute
  '/_admin/stock': typeof AdminStockRoute
  '/_admin/transactions': typeof AdminTransactionsRoute
  '/_admin/users': typeof AdminUsersRoute
  '/_auth/create': typeof AuthCreateRoute
  '/_auth/forgot': typeof AuthForgotRoute
  '/_auth/kyc': typeof AuthKycRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/operations': typeof AuthOperationsRoute
  '/_auth/sector': typeof AuthSectorRoute
  '/_auth/skip': typeof AuthSkipRoute
  '/_dashboard/buy-stocks': typeof DashboardBuyStocksRoute
  '/_dashboard/coin': typeof DashboardCoinRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/deposit': typeof DashboardDepositRoute
  '/_dashboard/discover': typeof DashboardDiscoverRoute
  '/_dashboard/history': typeof DashboardHistoryRoute
  '/_dashboard/logout': typeof DashboardLogoutRoute
  '/_dashboard/market-trends': typeof DashboardMarketTrendsRoute
  '/_dashboard/portfolio': typeof DashboardPortfolioRoute
  '/_dashboard/profile': typeof DashboardProfileRoute
  '/_dashboard/referrals': typeof DashboardReferralsRoute
  '/_dashboard/request': typeof DashboardRequestRoute
  '/_dashboard/stakes': typeof DashboardStakesRoute
  '/_dashboard/stock-deposit': typeof DashboardStockDepositRoute
  '/_dashboard/stock-withdraw': typeof DashboardStockWithdrawRoute
  '/_dashboard/stocks': typeof DashboardStocksRoute
  '/_dashboard/strategies': typeof DashboardStrategiesRoute
  '/_dashboard/watchlist': typeof DashboardWatchlistRoute
  '/_dashboard/withdraw': typeof DashboardWithdrawRoute
  '/_home/about': typeof HomeAboutRoute
  '/_home/contact': typeof HomeContactRoute
  '/_home/legal': typeof HomeLegalRoute
  '/_home/services': typeof HomeServicesRoute
  '/_home/': typeof HomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/adminProfile'
    | '/adminReferral'
    | '/depositRequests'
    | '/investments'
    | '/notifications'
    | '/plans'
    | '/requests'
    | '/settings'
    | '/staff'
    | '/stock'
    | '/transactions'
    | '/users'
    | '/create'
    | '/forgot'
    | '/kyc'
    | '/login'
    | '/operations'
    | '/sector'
    | '/skip'
    | '/buy-stocks'
    | '/coin'
    | '/dashboard'
    | '/deposit'
    | '/discover'
    | '/history'
    | '/logout'
    | '/market-trends'
    | '/portfolio'
    | '/profile'
    | '/referrals'
    | '/request'
    | '/stakes'
    | '/stock-deposit'
    | '/stock-withdraw'
    | '/stocks'
    | '/strategies'
    | '/watchlist'
    | '/withdraw'
    | '/about'
    | '/contact'
    | '/legal'
    | '/services'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/adminProfile'
    | '/adminReferral'
    | '/depositRequests'
    | '/investments'
    | '/notifications'
    | '/plans'
    | '/requests'
    | '/settings'
    | '/staff'
    | '/stock'
    | '/transactions'
    | '/users'
    | '/create'
    | '/forgot'
    | '/kyc'
    | '/login'
    | '/operations'
    | '/sector'
    | '/skip'
    | '/buy-stocks'
    | '/coin'
    | '/dashboard'
    | '/deposit'
    | '/discover'
    | '/history'
    | '/logout'
    | '/market-trends'
    | '/portfolio'
    | '/profile'
    | '/referrals'
    | '/request'
    | '/stakes'
    | '/stock-deposit'
    | '/stock-withdraw'
    | '/stocks'
    | '/strategies'
    | '/watchlist'
    | '/withdraw'
    | '/about'
    | '/contact'
    | '/legal'
    | '/services'
    | '/'
  id:
    | '__root__'
    | '/_admin'
    | '/_auth'
    | '/_dashboard'
    | '/_home'
    | '/_admin/adminProfile'
    | '/_admin/adminReferral'
    | '/_admin/depositRequests'
    | '/_admin/investments'
    | '/_admin/notifications'
    | '/_admin/plans'
    | '/_admin/requests'
    | '/_admin/settings'
    | '/_admin/staff'
    | '/_admin/stock'
    | '/_admin/transactions'
    | '/_admin/users'
    | '/_auth/create'
    | '/_auth/forgot'
    | '/_auth/kyc'
    | '/_auth/login'
    | '/_auth/operations'
    | '/_auth/sector'
    | '/_auth/skip'
    | '/_dashboard/buy-stocks'
    | '/_dashboard/coin'
    | '/_dashboard/dashboard'
    | '/_dashboard/deposit'
    | '/_dashboard/discover'
    | '/_dashboard/history'
    | '/_dashboard/logout'
    | '/_dashboard/market-trends'
    | '/_dashboard/portfolio'
    | '/_dashboard/profile'
    | '/_dashboard/referrals'
    | '/_dashboard/request'
    | '/_dashboard/stakes'
    | '/_dashboard/stock-deposit'
    | '/_dashboard/stock-withdraw'
    | '/_dashboard/stocks'
    | '/_dashboard/strategies'
    | '/_dashboard/watchlist'
    | '/_dashboard/withdraw'
    | '/_home/about'
    | '/_home/contact'
    | '/_home/legal'
    | '/_home/services'
    | '/_home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/services': {
      id: '/_home/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof HomeServicesRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/legal': {
      id: '/_home/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof HomeLegalRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/contact': {
      id: '/_home/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof HomeContactRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/about': {
      id: '/_home/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof HomeAboutRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_dashboard/withdraw': {
      id: '/_dashboard/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof DashboardWithdrawRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/watchlist': {
      id: '/_dashboard/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof DashboardWatchlistRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/strategies': {
      id: '/_dashboard/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof DashboardStrategiesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/stocks': {
      id: '/_dashboard/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof DashboardStocksRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/stock-withdraw': {
      id: '/_dashboard/stock-withdraw'
      path: '/stock-withdraw'
      fullPath: '/stock-withdraw'
      preLoaderRoute: typeof DashboardStockWithdrawRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/stock-deposit': {
      id: '/_dashboard/stock-deposit'
      path: '/stock-deposit'
      fullPath: '/stock-deposit'
      preLoaderRoute: typeof DashboardStockDepositRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/stakes': {
      id: '/_dashboard/stakes'
      path: '/stakes'
      fullPath: '/stakes'
      preLoaderRoute: typeof DashboardStakesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/request': {
      id: '/_dashboard/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof DashboardRequestRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/referrals': {
      id: '/_dashboard/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof DashboardReferralsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/profile': {
      id: '/_dashboard/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/portfolio': {
      id: '/_dashboard/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof DashboardPortfolioRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/market-trends': {
      id: '/_dashboard/market-trends'
      path: '/market-trends'
      fullPath: '/market-trends'
      preLoaderRoute: typeof DashboardMarketTrendsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/logout': {
      id: '/_dashboard/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof DashboardLogoutRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/history': {
      id: '/_dashboard/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/discover': {
      id: '/_dashboard/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DashboardDiscoverRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/deposit': {
      id: '/_dashboard/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof DashboardDepositRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/coin': {
      id: '/_dashboard/coin'
      path: '/coin'
      fullPath: '/coin'
      preLoaderRoute: typeof DashboardCoinRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/buy-stocks': {
      id: '/_dashboard/buy-stocks'
      path: '/buy-stocks'
      fullPath: '/buy-stocks'
      preLoaderRoute: typeof DashboardBuyStocksRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_auth/skip': {
      id: '/_auth/skip'
      path: '/skip'
      fullPath: '/skip'
      preLoaderRoute: typeof AuthSkipRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sector': {
      id: '/_auth/sector'
      path: '/sector'
      fullPath: '/sector'
      preLoaderRoute: typeof AuthSectorRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/operations': {
      id: '/_auth/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AuthOperationsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/kyc': {
      id: '/_auth/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof AuthKycRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot': {
      id: '/_auth/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/create': {
      id: '/_auth/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthCreateRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_admin/users': {
      id: '/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/transactions': {
      id: '/_admin/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/stock': {
      id: '/_admin/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AdminStockRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/staff': {
      id: '/_admin/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/requests': {
      id: '/_admin/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/plans': {
      id: '/_admin/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/notifications': {
      id: '/_admin/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/investments': {
      id: '/_admin/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof AdminInvestmentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/depositRequests': {
      id: '/_admin/depositRequests'
      path: '/depositRequests'
      fullPath: '/depositRequests'
      preLoaderRoute: typeof AdminDepositRequestsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/adminReferral': {
      id: '/_admin/adminReferral'
      path: '/adminReferral'
      fullPath: '/adminReferral'
      preLoaderRoute: typeof AdminAdminReferralRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/adminProfile': {
      id: '/_admin/adminProfile'
      path: '/adminProfile'
      fullPath: '/adminProfile'
      preLoaderRoute: typeof AdminAdminProfileRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAdminProfileRoute: typeof AdminAdminProfileRoute
  AdminAdminReferralRoute: typeof AdminAdminReferralRoute
  AdminDepositRequestsRoute: typeof AdminDepositRequestsRoute
  AdminInvestmentsRoute: typeof AdminInvestmentsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminStockRoute: typeof AdminStockRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminProfileRoute: AdminAdminProfileRoute,
  AdminAdminReferralRoute: AdminAdminReferralRoute,
  AdminDepositRequestsRoute: AdminDepositRequestsRoute,
  AdminInvestmentsRoute: AdminInvestmentsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminStockRoute: AdminStockRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthCreateRoute: typeof AuthCreateRoute
  AuthForgotRoute: typeof AuthForgotRoute
  AuthKycRoute: typeof AuthKycRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOperationsRoute: typeof AuthOperationsRoute
  AuthSectorRoute: typeof AuthSectorRoute
  AuthSkipRoute: typeof AuthSkipRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthCreateRoute: AuthCreateRoute,
  AuthForgotRoute: AuthForgotRoute,
  AuthKycRoute: AuthKycRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOperationsRoute: AuthOperationsRoute,
  AuthSectorRoute: AuthSectorRoute,
  AuthSkipRoute: AuthSkipRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardBuyStocksRoute: typeof DashboardBuyStocksRoute
  DashboardCoinRoute: typeof DashboardCoinRoute
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardDepositRoute: typeof DashboardDepositRoute
  DashboardDiscoverRoute: typeof DashboardDiscoverRoute
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardLogoutRoute: typeof DashboardLogoutRoute
  DashboardMarketTrendsRoute: typeof DashboardMarketTrendsRoute
  DashboardPortfolioRoute: typeof DashboardPortfolioRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardReferralsRoute: typeof DashboardReferralsRoute
  DashboardRequestRoute: typeof DashboardRequestRoute
  DashboardStakesRoute: typeof DashboardStakesRoute
  DashboardStockDepositRoute: typeof DashboardStockDepositRoute
  DashboardStockWithdrawRoute: typeof DashboardStockWithdrawRoute
  DashboardStocksRoute: typeof DashboardStocksRoute
  DashboardStrategiesRoute: typeof DashboardStrategiesRoute
  DashboardWatchlistRoute: typeof DashboardWatchlistRoute
  DashboardWithdrawRoute: typeof DashboardWithdrawRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardBuyStocksRoute: DashboardBuyStocksRoute,
  DashboardCoinRoute: DashboardCoinRoute,
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardDepositRoute: DashboardDepositRoute,
  DashboardDiscoverRoute: DashboardDiscoverRoute,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardLogoutRoute: DashboardLogoutRoute,
  DashboardMarketTrendsRoute: DashboardMarketTrendsRoute,
  DashboardPortfolioRoute: DashboardPortfolioRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardReferralsRoute: DashboardReferralsRoute,
  DashboardRequestRoute: DashboardRequestRoute,
  DashboardStakesRoute: DashboardStakesRoute,
  DashboardStockDepositRoute: DashboardStockDepositRoute,
  DashboardStockWithdrawRoute: DashboardStockWithdrawRoute,
  DashboardStocksRoute: DashboardStocksRoute,
  DashboardStrategiesRoute: DashboardStrategiesRoute,
  DashboardWatchlistRoute: DashboardWatchlistRoute,
  DashboardWithdrawRoute: DashboardWithdrawRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface HomeRouteRouteChildren {
  HomeAboutRoute: typeof HomeAboutRoute
  HomeContactRoute: typeof HomeContactRoute
  HomeLegalRoute: typeof HomeLegalRoute
  HomeServicesRoute: typeof HomeServicesRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeAboutRoute: HomeAboutRoute,
  HomeContactRoute: HomeContactRoute,
  HomeLegalRoute: HomeLegalRoute,
  HomeServicesRoute: HomeServicesRoute,
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  HomeRouteRoute: HomeRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
